// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHBfv1nSbUK1xuMj4rlTIFfCF1BwPxWd8',
    appId: '1:582242598073:web:28d355679a418c37caaf68',
    messagingSenderId: '582242598073',
    projectId: 'pushnotifications-90ee6',
    authDomain: 'pushnotifications-90ee6.firebaseapp.com',
    storageBucket: 'pushnotifications-90ee6.appspot.com',
    measurementId: 'G-1DYY3QF79S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHEEJsYH3FUcF00i8J-ifXhn_q8eK6Elo',
    appId: '1:582242598073:android:77bbe89e6e021fd8caaf68',
    messagingSenderId: '582242598073',
    projectId: 'pushnotifications-90ee6',
    storageBucket: 'pushnotifications-90ee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-for32y9XRsTxjgjzBG_Nu98norAgpo',
    appId: '1:582242598073:ios:2d2acf6bddd1793ccaaf68',
    messagingSenderId: '582242598073',
    projectId: 'pushnotifications-90ee6',
    storageBucket: 'pushnotifications-90ee6.appspot.com',
    iosBundleId: 'com.example.theme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-for32y9XRsTxjgjzBG_Nu98norAgpo',
    appId: '1:582242598073:ios:2d2acf6bddd1793ccaaf68',
    messagingSenderId: '582242598073',
    projectId: 'pushnotifications-90ee6',
    storageBucket: 'pushnotifications-90ee6.appspot.com',
    iosBundleId: 'com.example.theme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHBfv1nSbUK1xuMj4rlTIFfCF1BwPxWd8',
    appId: '1:582242598073:web:e8565cb8fbf5675acaaf68',
    messagingSenderId: '582242598073',
    projectId: 'pushnotifications-90ee6',
    authDomain: 'pushnotifications-90ee6.firebaseapp.com',
    storageBucket: 'pushnotifications-90ee6.appspot.com',
    measurementId: 'G-KD11K4VX6D',
  );
}
